<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BiogenomNutrition.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BiogenomNutrition.Application\BiogenomNutrition.Application.csproj" />
      <ProjectReference Include="..\BiogenomNutrition.Domain\BiogenomNutrition.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="EntityFramework" Version="6.5.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    </ItemGroup>

</Project>
